version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/AnuragDani/System_Design_Playground"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"